# Docker Compose for entire Full Stack Application running on localhost with locally built Docker Containers

version: '3.3'
services:
  # Frontend Service
  # movieland-frontend:
  #   container_name: movieland-frontend
  #   build:
  #     context: movieland-frontend
  #     dockerfile: Dockerfile
  #   image: movieland-frontend
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     PORT: 4000
  #   network_mode: host
  # Database Service (Postgresql)
  movieland-db:
    container_name: movieland-db
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=movielandadmin
      - POSTGRES_PASSWORD=movielandadmin
      - POSTGRES_DB=movieland_db
    volumes:
      - db-data:/var/lib/postgresql/data


# Volumes
volumes:
  db-data:

