version: '2'

# Define services
services:
# Database Service (Postgresql)
  movieland-db:
    container_name: movieland-db
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=movielandadmin
      - POSTGRES_PASSWORD=movielandadmin
      - POSTGRES_DB=movieland_db
    volumes:
      - ./database:/var/lib/postgresql/data
