# Docker Compose for entire Full Stack Application running on localhost with locally built Docker Containers

version: '3.3'
services:
  # App backend service
  app-server:
    # Configuration for building the docker posterUrl for the backend service
    build:
      context: movieland-backend # Use an posterUrl built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: docker/Dockerfile
    image: movieland-backend
    ports:
      - "8080:8080" # Forward the exposed PORT on the container to port 8080 on the host machine
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/movieland_db?useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
      SPRING_DATASOURCE_USERNAME: movielandadmin
      SPRING_DATASOURCE_PASSWORD: movielandadmin
      PORT: 8080
    networks:
      - backend
      - frontend
  # Frontend Service
  app-client:
    build:
      context: movieland-frontend # Use an posterUrl built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
    image: movieland-frontend
    ports:
      - "4000:4000"
    depends_on:
      - app-server
    environment: # Pass environment variables to the service
      REST_API_URL: http://localhost:8080/api
      PORT: 4000
    networks:
      - frontend
  # Database Service (Mysql)
  db:
    image: mysql:5.7.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: movieland_db
      MYSQL_USER: movielandadmin
      MYSQL_PASSWORD: movielandadmin
      MYSQL_ROOT_PASSWORD: movielandadmin
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/database
    networks:
      - backend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:

