# Docker Compose for entire Full Stack Application running on localhost with locally built Docker Containers

version: '3.3'
services:
  # App backend service
  movieland-backend:
    container_name: movieland-backend
    build:
      context: movieland-backend
      dockerfile: Dockerfile
    image: movieland-backend
    ports:
      - "8080:8080"
    depends_on:
      - movieland-db # This service depends on mysql. Start that first.
      - movieland-loki
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://movieland-db:5432/movieland_db?useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
      SPRING_DATASOURCE_USERNAME: movielandadmin
      SPRING_DATASOURCE_PASSWORD: movielandadmin
      SPRING_BOOT_ADMIN_CLIENT_URL: http://movieland-spring-admin:8081
      ZIPKIN_SERVER: movieland-tempo:9411
      LOKI_SERVER: movieland-loki:3100
      PORT: 8080
    networks:
      - backend
      - frontend
  # App backend service
  movieland-spring-admin:
    container_name: movieland-spring-admin
    build:
      context: movieland-spring-admin
      dockerfile: Dockerfile
    image: movieland-spring-admin
    ports:
      - "8081:8081"
    environment:
      PORT: 8081

    networks:
      - backend
  # Frontend Service
  movieland-frontend:
    container_name: movieland-frontend
    build:
      context: movieland-frontend
      dockerfile: Dockerfile
    image: movieland-frontend
    ports:
      - "4000:4000"
    depends_on:
      - movieland-backend
    environment:
      REST_API_URL: http://localhost:8080/api
      PORT: 4000
    networks:
      - frontend
  # Database Service (Postgresql)
  movieland-db:
    container_name: movieland-db
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=movielandadmin
      - POSTGRES_PASSWORD=movielandadmin
      - POSTGRES_DB=movieland_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  movieland-prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus-docker.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
    networks:
      - backend

  movieland-promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    volumes:
      - ./monitoring/promtail/promtail-docker.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - backend


  movieland-grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      PROMETHEUS_SERVER: http://movieland-prometheus:9090
      TEMPO_SERVER: http://movieland-tempo:3200
      LOKI_SERVER: http://movieland-loki:3100
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - movieland-prometheus
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
    user: "1000"
    networks:
      - backend
  # Source: https://github.com/marcingrzejszczak/observability-boot-blog-post
  movieland-tempo:
    container_name: tempo
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./monitoring/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
      - tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
    networks:
      - backend

  movieland-loki:
    container_name: loki
    image: grafana/loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://movieland-tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    networks:
      - backend

# Volumes
volumes:
  db-data:
  tempo-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:

