# Docker Compose for entire Full Stack Application running on localhost with locally built Docker Containers

version: '3.3'
services:
  # App backend service
  app-server:
    # Configuration for building the docker for the backend service
    build:
      context: movieland-backend
      dockerfile: docker/Dockerfile
    image: movieland-backend
    ports:
      - "8080:8080" # Forward the exposed PORT on the container to port 8080 on the host machine
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      - APP_HOST=0.0.0.0
      - APP_DATASOURCE_URL=postgresql://movielandadmin:movielandadmin@db:5432/movieland_db
      - APP_PORT=8080
    networks:
      - backend
      - frontend
  # Frontend Service
  app-client:
    build:
      context: movieland-frontend # Use an posterUrl built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
    image: movieland-frontend
    ports:
      - "4000:4000"
    depends_on:
      - app-server
    environment: # Pass environment variables to the service
      REST_API_URL: http://localhost:8080/api
      PORT: 4000
    networks:
      - frontend
  # Database Service (Postgresql)
  db:

    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=movielandadmin
      - POSTGRES_PASSWORD=movielandadmin
      - POSTGRES_DB=movieland_db
    volumes:
      #- db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend


# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:

