CREATE TABLE MOVIE(
  MOVIE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  RELEASE_DATE DATE,
  DESCRIPTION CHAR(128),
  POSTER_URL VARCHAR(256),
  TMDB_ID BIGINT
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(16) NOT NULL
);

CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SHOW_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL
);

CREATE TABLE MOVIE_SHOW(
  SHOW_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MOVIE_ID BIGINT NOT NULL,
  RELEASE_DATE DATETIME NOT NULL
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (SHOW_ID) REFERENCES MOVIE_SHOW(SHOW_ID) ON DELETE CASCADE;
ALTER TABLE RESERVATION ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE;

ALTER TABLE MOVIE_SHOW ADD FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID) ON DELETE CASCADE;

CREATE INDEX IDX_RES_DATE_ ON MOVIE_SHOW(RELEASE_DATE);
