/*CREATE TABLE MOVIE(
  MOVIE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  RELEASE_DATE DATE,
  DESCRIPTION CHAR(128),
  POSTER_URL VARCHAR(256),
  TMDB_ID BIGINT
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(16) NOT NULL
);

CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SHOW_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL
);

CREATE TABLE MOVIE_SHOW(
  SHOW_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MOVIE_ID BIGINT NOT NULL,
  RELEASE_DATE DATETIME NOT NULL
);



ALTER TABLE RESERVATION ADD FOREIGN KEY (SHOW_ID) REFERENCES MOVIE_SHOW(SHOW_ID) ON DELETE CASCADE;
ALTER TABLE RESERVATION ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE;

ALTER TABLE MOVIE_SHOW ADD FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID) ON DELETE CASCADE;

CREATE INDEX IDX_RES_DATE_ ON MOVIE_SHOW(RELEASE_DATE);*/

CREATE TABLE USER
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     CHAR(32) NOT NULL,
    username CHAR(32) NOT NULL,
    email    CHAR(40) NOT NULL,
    password CHAR(64) NOT NULL

);

CREATE TABLE ROLE
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name ENUM ('USER','ADMIN')
);

CREATE TABLE USER_ROLES
(
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

ALTER TABLE USER_ROLES
    ADD FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE;
ALTER TABLE USER_ROLES
    ADD FOREIGN KEY (role_id) REFERENCES ROLE (id) ON DELETE CASCADE;