version: '2'

# Define services
services:
# Database Service (Postgresql)
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=movielandadmin
      - POSTGRES_PASSWORD=movielandadmin
      - POSTGRES_DB=movieland_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./resetTestDB.sql:/docker-entrypoint-initdb.d/init.sql

# Volumes
volumes:
  db-data: