global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:

  - job_name: 'movieland-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: movieland-api
    tls_config:
      insecure_skip_verify: true