global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'movieland-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['movieland-backend:8080']
        labels:
          application: movieland-api