apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: $PROMETHEUS_SERVER
      editable: false
      jsonData:
        httpMethod: POST
        exemplarTraceIdDestinations:
          - name: trace_id
            datasourceUid: tempo
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: $TEMPO_SERVER
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
      jsonData:
          httpMethod: GET
          tracesToLogs:
              datasourceUid: 'loki'
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      orgId: 1
      url: $LOKI_SERVER
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
      apiVersion: 1
      jsonData:
          derivedFields:
              -   datasourceUid: tempo
                  matcherRegex: \[.+,(.+?),
                  name: TraceID
                  url: $${__value.raw}
