apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app-client
  name: app-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app-client
    spec:
      containers:
        - image: philkes/movie-land-frontend:master
          name: app-client
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
